# -*- coding: utf-8 -*-
from datetime import datetime
from .time_group import TimeGroup

__all__ = ["MMUT_MAP", "LOC_METHOD"]

# 按多index获取df中的数据
LOC_METHOD = {
    -2: lambda d, i, k: d.loc[(i[0], "1900-01-01")][k],  # 时间聚合
    -1: lambda d, i, k: d.loc[(i[0], datetime.strptime(i[1], "%Y-%m-%d").timetuple().tm_yday)][k],  # 区域聚合
    2: lambda d, i, k: d.loc[(i[0], datetime.strptime(i[1], "%Y-%m-%d").timetuple().tm_yday)][k],
    3: lambda d, i, k: d.loc[(i[0], (int(i[1].split("/")[1]) - 1) * 6 + int(i[1].split("/")[2]))][k],
    4: lambda d, i, k: d.loc[(i[0], (int(i[1].split("/")[1]) - 1) * 3 + int(i[1].split("/")[2]))][k],
    5: lambda d, i, k: d.loc[(i[0], int(i[1].split("-")[-1]))][k],
    6: lambda d, i, k: d.loc[(i[0], TimeGroup.get_season_seq_by(i[1].split("年")[-1]))][k],
    7: lambda d, i, k: d.loc[(i[0], "19812010")][k]
}

MMUT_MAP = {
    2: {
        "d": "date",
        "date": "day_seq",
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_2008': "pre_time_2008",  # 暂替
        'pre_time_0808': "pre_time_0808_mmut",
        'pre_time_0820': "pre_time_0820",  # 暂替
        'tem_avg': "tem_avg",
        'tem_max': "tem_max_avg_mmut",
        'tem_min': "tem_min_avg_mmut",
        "tem_avg_5d": "tem_avg_5d",
        "prs_avg": "prs_avg",
        "prs_max": "prs_max",
        "prs_min": "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max_avg_mmut",
        'gst_min': "gst_min_avg_mmut",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    },
    3: {
        "d": "pentad",
        'date': 'pen_seq',
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_2008': "pre_time_2020_mmut",  # 暂替
        'pre_time_0808': "pre_time_0808_mmut",
        'pre_time_0820': "pre_time_0808_mmut",  # 暂替
        'tem_avg': "tem_avg",
        'tem_max': "tem_max",
        'tem_min': "tem_min",
        "prs_avg": "prs_avg",
        "prs_max": "prs_max",
        "prs_min": "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max_avg_mmut",
        'gst_min': "gst_min_avg_mmut",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    },
    4: {
        'd': 'i10days',
        'date': 'ten_seq',
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_2008': "pre_time_2008",  # 暂替
        'pre_time_0808': "pre",
        'pre_time_0820': "pre_time_0820",  # 暂替
        'tem_avg': "tem_avg",
        'tem_max': "tem_max",
        'tem_min': "tem_min",
        'prs_avg': "prs_avg",
        'prs_max': "prs_max",
        'prs_min': "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max",
        'gst_min': "gst_min",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    },
    5: {
        'd': 'month',
        'date': 'mon_seq',
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_0808': "pre_time_2020_mmut",  # qy新算的值中只有pre 其替代的per_time_2020_mmut
        'pre_time_0820': "pre_time_2020_mmut",  # qy新算的值中只有pre 其替代的per_time_2020_mmut
        'pre_time_2008': "pre_time_2020_mmut",  # qy新算的值中只有pre 其替代的per_time_2020_mmut
        'tem_avg': "tem_avg",
        'tem_max': "tem_max",
        'tem_min': "tem_min",
        'prs_avg': "prs_avg",
        'prs_max': "prs_max",
        'prs_min': "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max_avg_mmut",
        'gst_min': "gst_min_avg_mmut",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp_mon",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    },
    6: {
        'd': 'season',
        'date': 'season_seq',
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_2008': "pre_time_2020_mmut",  # 暂替
        'pre_time_0808': "pre_time_0808_mmut",
        'pre_time_0820': "pre_time_0808_mmut",  # 暂替
        'tem_avg': "tem_avg",
        'tem_max': "tem_max",
        'tem_min': "tem_min",
        "prs_avg": "prs_avg",
        "prs_max": "prs_max",
        "prs_min": "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max_avg_mmut",
        'gst_min': "gst_min_avg_mmut",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    },
    7: {
        "d": "year",
        "date": "years_mmut",
        "station": "station",
        'pre_time_2020': "pre_time_2020_mmut",
        'pre_time_2008': "pre_time_2020_mmut",  # 暂替
        'pre_time_0808': "pre_time_2020_mmut",
        'pre_time_0820': "pre_time_2020_mmut",  # 暂替
        'tem_avg': "tem_avg",
        'tem_max': "tem_max",
        'tem_min': "tem_min",
        'prs_avg': "prs_avg",
        'prs_max': "prs_max",
        'prs_min': "prs_min",
        "rhu_avg": "rhu_avg",
        "rhu_min": "rhu_min",
        'win_s': "win_s_avg",
        'win_s_max': "win_s_max",
        'win_s_inst_max': "win_s_inst_max",
        'win_s_2mi_avg': "win_s_2mi",
        'win_s_10mi_avg': "win_s_10mi",
        'gst_avg': "gst_avg",
        'gst_max': "gst_max_avg_mmut",
        'gst_min': "gst_min_avg_mmut",
        'gst_avg_5cm': "gst_avg_5cm",
        'gst_avg_10cm': "gst_avg_10cm",
        'gst_avg_15cm': "gst_avg_15cm",
        'gst_avg_20cm': "gst_avg_20cm",
        'gst_avg_40cm': "gst_avg_40cm",
        "ssh": "ssh",
        "ssp": "ssp",
        'vap_avg': "vap_avg",
        'evp': "evp",
        'evp_big': "evp",  # 暂替
        'frs_1st_top': 'frs_1st_top',
        'v20330_01': 'frs_1st_top',
        'frs_1st_bot': 'frs_1st_bot',
        'v20331_01': 'frs_1st_bot',
        'frs_2nd_top': 'frs_2nd_top',
        'v20330_02': 'frs_2nd_top',
        'frs_2nd_bot': 'frs_2nd_bot',
        'v20331_02': 'frs_2nd_bot',
        "snow_depth": "snow_depth",
        "v13013": "snow_depth",
        "snow_prs": "snow_prs",
        "v13330": "snow_prs",
    }
}
